### ISSUE TITLE
This code doesn't work with Notification version 7.0.3

### ISSUE THREAD

**Issue by sagashiftyblow** [BracketSpace/Notification-Docs#1]
This code (https://github.com/BracketSpace/Notification-Docs/blob/7/developer/snippets/triggers/post.md) doesn't work with Notification version 7.0.3. Could this be checked out?

**Comment by jakubmikita** [comment]
Thanks for the info! I just read all the docs again and fixed the incompatibility. It was a problem with the trigger slug.
